name: "Build Commit"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-java@v3.10.0
        with:
          distribution: temurin
          java-version: 17

      - name: Configure Keystore Properties
        run: |
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> signature/keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> signature/keystore.properties

      - uses: gradle/gradle-build-action@v2.4.2
      - run: gradle assembleRelease

      - uses: actions/upload-artifact@v4
        with:
          name: Bibliotecat-GitHub-Build-${{ github.sha }}
          path: app/release/*.apk
